### ISSUE TITLE
metadata tags still aren't parsed properly if there is more than one ; or : in the tag

### ISSUE THREAD

**Issue by Luckless** [keirans/azuremetadata#24]
We found that the module works if there is one ; or : in the tag value but not more than that.

Solution would be to update the version of the metadata api and parse new tagList json instead of splitting on the tag string

**Comment by Luckless** [comment]
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service

2019-08-15 is the latest api in GA for all regions. but 2019-06-04 gets the job done

**Comment by keirans** [comment]
Hey There,
Thanks for this,  I don't use Azure much anymore, however i'll roll and update through for this and another PR thats come through today.

I'll also update the readme around updating the contribution workflow so we can easily roll fixes in.

If you havent jumped in the Puppet JIRA tickets in the readme to ask about this being merged into Facter mainline, can you do that as well ?  (please :) ) 

Thanks!

**Comment by keirans** [comment]
I've bumped the version to 0.2.0 and sunset the tags functionality of the code, so won't fix this issue.

This is because the tags namespace we introduced in the original module now collides with a value of the same name exposed directly from the Azure Metadata service, in addition to this, the service provides a new value called tagsList that is an array of hashed key/value pairs for your tags that is much cleaner and maintainable.

Thanks for raising this.
